"""initial migration

Revision ID: 54abd7745bcc
Revises: 
Create Date: 2026-01-19 23:37:14.476953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54abd7745bcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_case_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_magsafe', sa.Boolean(), nullable=False),
    sa.Column('is_double_layer', sa.Boolean(), nullable=False),
    sa.Column('customization_data', sa.JSON(), nullable=True),
    sa.Column('design_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_case_types')),
    sa.UniqueConstraint('type_name', name=op.f('uq_phone_case_types_type_name'))
    )
    op.create_index(op.f('ix_phone_case_types_id'), 'phone_case_types', ['id'], unique=False)
    op.create_table('phone_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_models')),
    sa.UniqueConstraint('model_code', name=op.f('uq_phone_models_model_code'))
    )
    op.create_index(op.f('ix_phone_models_id'), 'phone_models', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=False),
    sa.Column('customization_data', sa.JSON(), nullable=True),
    sa.Column('design_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('orderer_name', sa.String(length=100), nullable=False),
    sa.Column('orderer_email', sa.String(length=100), nullable=False),
    sa.Column('orderer_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['phone_case_types.id'], name=op.f('fk_orders_case_type_id_phone_case_types')),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], name=op.f('fk_orders_phone_model_id_phone_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_phone_models_id'), table_name='phone_models')
    op.drop_table('phone_models')
    op.drop_index(op.f('ix_phone_case_types_id'), table_name='phone_case_types')
    op.drop_table('phone_case_types')
    # ### end Alembic commands ###