"""fix relations

Revision ID: 6a1d9bed1a9e
Revises: c853c46159f8
Create Date: 2026-01-25 14:29:14.564273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a1d9bed1a9e'
down_revision: Union[str, None] = 'c853c46159f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['phone_case_types.id'], name=op.f('fk_phone_cases_case_type_id_phone_case_types')),
    sa.ForeignKeyConstraint(['phone_model_id'], ['phone_models.id'], name=op.f('fk_phone_cases_phone_model_id_phone_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_cases')),
    sa.UniqueConstraint('phone_model_id', 'case_type_id', name='uq_phone_cases_model_type'),
    sa.UniqueConstraint('sku', name=op.f('uq_phone_cases_sku'))
    )
    op.create_index(op.f('ix_phone_cases_id'), 'phone_cases', ['id'], unique=False)
    op.create_table('used_phone_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_model_id', sa.Integer(), nullable=False),
    sa.Column('case_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['used_phone_case_types.id'], name=op.f('fk_used_phone_cases_case_type_id_used_phone_case_types')),
    sa.ForeignKeyConstraint(['phone_model_id'], ['used_phone_models.id'], name=op.f('fk_used_phone_cases_phone_model_id_used_phone_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_used_phone_cases')),
    sa.UniqueConstraint('phone_model_id', 'case_type_id', name='uq_used_phone_cases_model_type')
    )
    op.create_index(op.f('ix_used_phone_cases_id'), 'used_phone_cases', ['id'], unique=False)
    op.create_table('phone_case_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_case_id', sa.Integer(), nullable=False),
    sa.Column('base_image_url', sa.String(length=500), nullable=False),
    sa.Column('print_mask_url', sa.String(length=500), nullable=False),
    sa.Column('overlay_image_url', sa.String(length=500), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('bleed_mm', sa.Float(), nullable=True),
    sa.Column('safe_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phone_case_id'], ['phone_cases.id'], name=op.f('fk_phone_case_templates_phone_case_id_phone_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_case_templates')),
    sa.UniqueConstraint('phone_case_id', name='uq_phone_case_templates_phone_case_id')
    )
    op.create_index(op.f('ix_phone_case_templates_id'), 'phone_case_templates', ['id'], unique=False)
    op.create_table('used_phone_case_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_case_id', sa.Integer(), nullable=False),
    sa.Column('base_image_url', sa.String(length=500), nullable=False),
    sa.Column('print_mask_url', sa.String(length=500), nullable=False),
    sa.Column('overlay_image_url', sa.String(length=500), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phone_case_id'], ['used_phone_cases.id'], name=op.f('fk_used_phone_case_templates_phone_case_id_used_phone_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_used_phone_case_templates')),
    sa.UniqueConstraint('phone_case_id', name='uq_phone_case_templates_case_id')
    )
    op.create_index(op.f('ix_used_phone_case_templates_id'), 'used_phone_case_templates', ['id'], unique=False)
    op.add_column('orders', sa.Column('phone_case_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('customization_json', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('preview_image_url', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('print_image_url', sa.String(length=500), nullable=True))
    # Backfill phone_case_id for existing orders using (phone_model_id, case_type_id)
    op.execute("""
        INSERT INTO phone_cases (phone_model_id, case_type_id, created_at, updated_at)
        SELECT DISTINCT o.phone_model_id, o.case_type_id, NOW(), NOW()
        FROM orders o
        WHERE o.phone_model_id IS NOT NULL AND o.case_type_id IS NOT NULL
        ON CONFLICT (phone_model_id, case_type_id) DO NOTHING
    """)
    op.execute("""
        UPDATE orders o
        SET phone_case_id = pc.id
        FROM phone_cases pc
        WHERE o.phone_case_id IS NULL
          AND o.phone_model_id = pc.phone_model_id
          AND o.case_type_id = pc.case_type_id
    """)
    op.drop_constraint(op.f('fk_orders_case_type_id_phone_case_types'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_phone_model_id_phone_models'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_phone_case_id_phone_cases'), 'orders', 'phone_cases', ['phone_case_id'], ['id'])
    op.alter_column('orders', 'phone_case_id', nullable=False)
    op.drop_column('orders', 'case_type_id')
    op.drop_column('orders', 'phone_model_id')
    op.drop_column('phone_case_types', 'customization_data')
    op.drop_column('phone_case_types', 'design_image_url')
    op.drop_column('used_phone_case_types', 'image_url')
    op.drop_constraint(op.f('fk_used_phone_models_phone_case_id_used_phone_case_types'), 'used_phone_models', type_='foreignkey')
    op.drop_column('used_phone_models', 'phone_case_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('used_phone_models', sa.Column('phone_case_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_used_phone_models_phone_case_id_used_phone_case_types'), 'used_phone_models', 'used_phone_case_types', ['phone_case_id'], ['id'])
    op.add_column('used_phone_case_types', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('phone_case_types', sa.Column('design_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('phone_case_types', sa.Column('customization_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('phone_model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('case_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_orders_phone_case_id_phone_cases'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_phone_model_id_phone_models'), 'orders', 'phone_models', ['phone_model_id'], ['id'])
    op.create_foreign_key(op.f('fk_orders_case_type_id_phone_case_types'), 'orders', 'phone_case_types', ['case_type_id'], ['id'])
    op.drop_column('orders', 'print_image_url')
    op.drop_column('orders', 'preview_image_url')
    op.drop_column('orders', 'customization_json')
    op.drop_column('orders', 'phone_case_id')
    op.drop_index(op.f('ix_used_phone_case_templates_id'), table_name='used_phone_case_templates')
    op.drop_table('used_phone_case_templates')
    op.drop_index(op.f('ix_phone_case_templates_id'), table_name='phone_case_templates')
    op.drop_table('phone_case_templates')
    op.drop_index(op.f('ix_used_phone_cases_id'), table_name='used_phone_cases')
    op.drop_table('used_phone_cases')
    op.drop_index(op.f('ix_phone_cases_id'), table_name='phone_cases')
    op.drop_table('phone_cases')
    # ### end Alembic commands ###