"""add status field to admin table

Revision ID: 7eed95fd2dc4
Revises: 18e7513a4842
Create Date: 2026-03-18 01:55:44.505471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eed95fd2dc4'
down_revision: Union[str, None] = '18e7513a4842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admin_status = sa.Enum('ACTIVE', 'INACTIVE', name='adminstatus')
    admin_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'admins',
        sa.Column('status', admin_status, nullable=False, server_default='ACTIVE')
    )
    op.alter_column('admins', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admin_status = sa.Enum('ACTIVE', 'INACTIVE', name='adminstatus')
    op.drop_column('admins', 'status')
    admin_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###