"""add phones tables

Revision ID: c853c46159f8
Revises: 49b5015505e4
Create Date: 2026-01-24 15:14:26.556416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c853c46159f8'
down_revision: Union[str, None] = '49b5015505e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_phone_case_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_magsafe', sa.Boolean(), nullable=False),
    sa.Column('is_double_layer', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_used_phone_case_types'))
    )
    op.create_index(op.f('ix_used_phone_case_types_id'), 'used_phone_case_types', ['id'], unique=False)
    op.create_table('used_phone_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('phone_case_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phone_case_id'], ['used_phone_case_types.id'], name=op.f('fk_used_phone_models_phone_case_id_used_phone_case_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_used_phone_models'))
    )
    op.create_index(op.f('ix_used_phone_models_id'), 'used_phone_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_phone_models_id'), table_name='used_phone_models')
    op.drop_table('used_phone_models')
    op.drop_index(op.f('ix_used_phone_case_types_id'), table_name='used_phone_case_types')
    op.drop_table('used_phone_case_types')
    # ### end Alembic commands ###