"""updated model2

Revision ID: f306f12a40ca
Revises: 7e550ee54648
Create Date: 2026-01-21 00:33:07.891780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f306f12a40ca'
down_revision: Union[str, None] = '7e550ee54648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customization_data')
    op.drop_column('orders', 'design_image_url')
    op.drop_constraint(op.f('uq_phone_case_types_type_name'), 'phone_case_types', type_='unique')
    op.drop_constraint(op.f('uq_phone_models_model_code'), 'phone_models', type_='unique')
    op.drop_column('phone_models', 'model_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_models', sa.Column('model_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_phone_models_model_code'), 'phone_models', ['model_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_phone_case_types_type_name'), 'phone_case_types', ['type_name'], postgresql_nulls_not_distinct=False)
    op.add_column('orders', sa.Column('design_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customization_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###