# strings.py
USER_ALREADY_EXISTS ='User already exists.'
USER_INVALID_CREDENTIALS = 'Invalid credentials.'
USER_PENDING = 'ACCOUNT PENDING APPROVAL.'
UNAUTHORIZED_USER = 'Unauthorized User.'
INACTIVE_USER = 'Inactive user.'
NO_CREDENTIALS= 'Could not validate credentials.'
MANY_REQUESTS= 'Too many requests. Try again later.'
PASSWORDS_NOT_MATCH= 'Passwords do not match.'
INVALID_CODE= 'Invalid verification code.'
SENT_SUCCESSFULLY= 'Verification code sent successfully'
INVALID_EAMIL= 'An account with this email does not exist'
NO_USER= 'User does not does not exist'
DELETED_ACCOUNT= 'Deleted Account'
